# Generated by Django 3.2.7 on 2021-09-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210922_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='locality',
            field=models.CharField(default='NA', max_length=255),
        ),
    ]
